NoMethodError fixed
When I run rspec I've got error:
foodtaster-example ⮀ rspec spec
/foodtaster-example/spec/spec_helper.rb:10:in `block in <top (required)>': undefined method `shutdown_vms=' for #<Foodtaster::Config:0x00000100852ec8> (NoMethodError)